name: Run Tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install deps
        run: pip install -r requirements.txt pytest
      - name: Run tests
        run: PYTHONPATH=. pytest
